name: Check Commit
on: [push]

jobs:
  check-commit:
    name: Check Commit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Check pre-commit
        run: uvx pre-commit run --all-files
